android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx8192M \ -XX:MaxMetaspaceSize=2048M \ -XX:+HeapDumpOnOutOfMemoryError \ -Dfile.encoding=UTF-8
# org.gradle.jvmargs=-Xms1024m -Xmx4096m
android.enableR8=true
kotlin.jvm.target=1.8
ANDROID_NDK_HOME=/Users/sudhir.patil/Library/Android/sdk/ndk/
ANDROID_HOME=/Users/sudhir.patil/Library/Android/sdk/
android.ndkVersion=28.2.13676358
android.experimental.enableSourceSetPathsMap=true
# org.gradle.parallel=true
# org.gradle.configureondemand=true
# android.jetifier.ignorelist=bcprov-jdk18on-1.78.1.jar
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

kotlin.jvm.target.validation.mode=IGNORE

kotlin.code.style=official
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.caching=true