// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
//       debugPrint('Android platform detected');
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7hds0TPnnZ5vGRNTRAxRDuUs1eBbbyI',
    appId: '1:66383917412:web:606a822f710e21409eca71',
    messagingSenderId: '66383917412',
    projectId: 'kidzeeandroidapp-91faf',
    authDomain: 'kidzeeandroidapp-91faf.firebaseapp.com',
    databaseURL: 'https://kidzeeandroidapp-91faf.firebaseio.com',
    storageBucket: 'kidzeeandroidapp-91faf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLy7C69KVA6inKnpAkNc5g8WL1EMURLws',
    appId: '1:66383917412:android:cad5aa524168ec6f',
    messagingSenderId: '66383917412',
    projectId: 'kidzeeandroidapp-91faf',
    databaseURL: 'https://kidzeeandroidapp-91faf.firebaseio.com',
    storageBucket: 'kidzeeandroidapp-91faf.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJj0-2iGJEySUvmZr_dyFl5X3C1igwR-8',
    appId: '1:66383917412:ios:cad5aa524168ec6f',
    messagingSenderId: '66383917412',
    projectId: 'kidzeeandroidapp-91faf',
    databaseURL: 'https://kidzeeandroidapp-91faf.firebaseio.com',
    storageBucket: 'kidzeeandroidapp-91faf.appspot.com',
    androidClientId: '66383917412-00sjf7i92ubq8rb4r1bj2fio9qbov24g.apps.googleusercontent.com',
    iosClientId: '66383917412-b8235k1t8o9m2rsndo5tc9btlji34rh0.apps.googleusercontent.com',
    iosBundleId: 'com.zeelearn.ekidzee',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJj0-2iGJEySUvmZr_dyFl5X3C1igwR-8',
    appId: '1:66383917412:ios:cad5aa524168ec6f',
    messagingSenderId: '66383917412',
    projectId: 'kidzeeandroidapp-91faf',
    databaseURL: 'https://kidzeeandroidapp-91faf.firebaseio.com',
    storageBucket: 'kidzeeandroidapp-91faf.appspot.com',
    androidClientId: '66383917412-00sjf7i92ubq8rb4r1bj2fio9qbov24g.apps.googleusercontent.com',
    iosClientId: '66383917412-b8235k1t8o9m2rsndo5tc9btlji34rh0.apps.googleusercontent.com',
    iosBundleId: 'com.zeelearn.ekidzee',
  );
}
